apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: g6gl7qif8-java-springboot
  janus-idp.io/tekton: g6gl7qif8-java-springboot
  backstage.io/kubernetes-id: g6gl7qif8-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: g6gl7qif8-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
